@startuml
title 음료주문

actor "User" as user
participant "App" as app
participant "BackEnd" as backend
participant "RDBMS" as db


user -> app : 주문하기
activate user
activate app
app -> app : 매장선택
group success flow
    app -[#blue]> backend : 주문요청(req)
    activate backend
    backend -[#blue]> backend : 주문확인\n(유효성검사)

    group invalidate
        backend --[#red]x app : 주문재확인
    end

    backend -[#blue]> backend : 주문확인\n(매장확인)

    group not store
        backend --[#red]x app : 매장 재선택
        note left : 주문 전, 매장을 선택하지 않은 경우
    end

    group out of store
        backend --[#red]x app : 매장 재선택
        note left : 나와 매장의 거리가 5km 이상
    end

    backend -[#blue]> backend : 매장선택 완료
    backend -[#blue]> db : 주문정보 저장
    activate db
    db -[#blue]> backend : 쿼리성공
    deactivate db
    backend -[#blue]> app : 주문완료(res)
    deactivate backend
    deactivate app
end
@enduml