@startuml
!define APP class backgroundColor LightSkyBlue
!define STORE class backgroundColor PaleGreen
!define ORDER class backgroundColor LightCyan
!define PAYMENT class backgroundColor LightGoldenRodYellow

title 주문 시퀀스


actor Customer as customer

box "App"
participant "Customer" as app
participant "Store" as storeSelection
participant "Order-1" as order_1
participant "Order-2" as order_2
participant "Payment" as payment
end box
database PaymentSystem as paymentSystem


customer -> app: app 접속
app -> order_1 : [주문 버튼] 클릭
order_1 -> storeSelection: 주문할 매장 선택
storeSelection -> app: 매장 선택완료
app -> order_1: [전체 메뉴] 클릭
app -> order_1: [음료 카테고리] 클릭
app -> order_1: [음료 종류 카테고리] 클릭
app -> order_1: [실제 음료] 클릭
app -> order_1: [ICE, HOT] 선택
order_1 -> order_2: [주문 하기] 클릭
order_1 -> order_2: [음료 사이즈] 선택
order_1 -> order_2: [음료 컵] 선택
order_1 -> order_2: [음료 수량] 선택
order_2 -> payment: [결제 하기] 클릭
order_2 -> payment: 결제 수단 선택
order_2 -> payment: 쿠폰 및 할인 선택
order_2 -> payment: 결제 하기
payment -> storeSelection
storeSelection -> payment : 매장 다시 확인
payment -> paymentSystem: 결제 시스템 연동
@enduml
