@startuml
title 알림센터


actor "User" as user
participant "App" as app
participant "BackEnd" as backend
participant "REDIS\n(주문TB)" as redis
database "paymentSystem" as paySystem
participant "FCM" as fcm
actor "Store" as store

activate user

group success flow

backend -[#blue]> fcm : 음료제조 요청
activate backend

activate fcm
fcm -[#blue]> store : 주문확인 요청
activate store
    group order cancellation
        store --[#red]x fcm : 주문취소 요청
        fcm --[#red]x backend : 주문취소
        backend --[#green]> paySystem : 결제취소
        paySystem --[#green]> backend : 결제취소 완료
        backend --[#green]> redis : 주문(취소)변경 요청
        redis --[#green]> backend : 주문변경 완료
        backend --[#red]> app : 주문취소\n(rollback)
    end
store -[#blue]> fcm : 주문확인 응답
fcm -[#blue]> fcm : [주문완료] 상태변경

fcm -[#blue]> app : [주문완료] 알림
activate app
user --[#blue]> app : 알림확인
deactivate app

    group user request
        user --[#blue]> app : 주문상태 요청(req)
        activate app
        note right : 유저가 주문현황을 확인할 때
        app -[#blue]> backend : 주문상태 확인
        backend <-[#blue]> fcm : 주문상태 요청/응답 (주문완료)
        backend -[#blue]> app : 주문상태 반환
        app --[#blue]> user : [주문완료](res)
        deactivate app
    end
store -[#blue]> store : 음료준비중
store -[#blue]> fcm : 음료준비중
fcm -[#blue]> fcm : [음료준비중] 상태변경
    group user request
        user --[#blue]> app : 주문상태 요청(req)
        activate app
        note right : 유저가 주문현황을 확인할 때
        app -[#blue]> backend : 주문상태 확인
        backend <-[#blue]> fcm : 주문상태 요청/응답 (음료준비중)
        backend -[#blue]> app : 주문상태 반환
        app --[#blue]> user : [음료준비](res)
        deactivate app
    end

store -[#blue]> store : 음료완료
store -[#blue]> fcm : 음료완료
deactivate store
fcm -[#blue]> fcm : [픽업대기] 상태변경
fcm -[#blue]> app : [픽업대기] 알림
activate app
user --[#blue]> app : 알림확인
deactivate app

    group user request
        user --[#blue]> app : 주문상태 요청(req)
        activate app
        note right : 유저가 주문현황을 확인할 때
        app -[#blue]> backend : 주문상태 확인
        backend <-[#blue]> fcm : 주문상태 요청/응답 (픽업대기)
        backend -[#blue]> app : 주문상태 반환
        app --[#blue]> user : [픽업대기](res)
        deactivate app
        deactivate fcm
        deactivate backend
    end

deactivate user
end

@enduml